#New paramenters can be found and added at this site: https://technet.microsoft.com/en-us/library/ee617253.aspx
#Sweet ASCII Art generated by http://patorjk.com/software/taag

#CSV2AD-USERS Creates new active directories from a CSV file.

#Author: Jannis Kirschner
#Copyrigt: GNU General Public License v3.0

#Ascii Art
$welcome = "      
                  ____ ______     ______     _    ____        _   _ ____  _____ ____  ____  
                 / ___/ ___\ \   / /___ \   / \  |  _ \      | | | / ___|| ____|  _ \/ ___| 
                | |   \___ \\ \ / /  __) | / _ \ | | | |_____| | | \___ \|  _| | |_) \___ \ 
                | |___ ___) |\ V /  / __/ / ___ \| |_| |_____| |_| |___) | |___|  _ < ___) |
                 \____|____/  \_/  |_____/_/   \_\____/       \___/|____/|_____|_| \_\____/ 
                                                   https://github.com/JannisKirschner `n `n "  
 



#Initialises the script with a message
Write-Host $welcome
Write-Host "Welcome to CSV2AD-USERS - The tool to create AD-Users out of CSV files" `n

#Select the delimiter to seperate the parameters
Write-Host "Please select a delimiter (0 = ;  |  1 = ,)"


#Inputs the delimiter style (with error handling)
While($True){
    $delimiterchoice = Read-Host "Delimiter>"
    If($delimiterchoice -eq 0){$delimiter = ";" ; break}
    ElseIf($delimiterchoice -eq 1){$delimiter = "," ; break}
    Else{Write-Host "Bad input!" -foreground red}
}

#Imports the CSV-File
$adparams = Import-CSV  „C:\Users\Administrator\Desktop\x.csv“ -delimiter $delimiter

#Asks for permission to create the users (with error handling)
Write-Host "Are you sure you want to create the following user(s): " `n

Foreach($user in $adparams){
    $name = $user.Name
    Write-Host $name
}

While($True){
    $prompt = Read-Host "(y/n)>"
    $proceed = "y"
    $cancel = "n"


    If($prompt -eq $proceed){

            #Inputs the domain name (with error handling)
            #Please enter it <domain>.<top-level domain> "testdomain.com"
            While($True){
            
                $domain = Read-Host "Please enter (full) domain-name> "
                $verifydomain = Read-Host "Please reenter your domain-name> "
                if($domain -eq $verifydomain){break}
                else{Write-Host "Domains are not matching, please try again!" -foreground red }
            }
            
            #Inputs the default user password (with error handling)
            While($True){
            
                $passwordinput = Read-Host "Please enter the default password> " 
                $verifypassword = Read-Host "Please reenter the default password> " 
                if($passwordinput -eq $verifypassword){break}
                else{Write-Host "Passwords are not matching, please try again!" -foreground red }
            }

            
            #Inputs the Organistation-Unit name (with error handling) #TODO Multiple OU Layers
            While($True){
            
                $ouname = Read-Host "Please enter the OU-Name> " 
                $verifyou = Read-Host "Please enter the OU-Name again> " 
                if($ouname -eq $verifyou){break}
                else{Write-Host "OU-Names are not matching, please try again!" -foreground red }
            }


            #Prepares the OU path 
            $tempou = $domain.split(".") 
            $oudomain = $tempou[0]
            $outld = $tempou[1]
            
            
            Write-Host "Creating AD-User(s)..." -foreground yellow `n `n 

        #Processes the recently created statements and creates the users
        try{
            Foreach($user in $adparams ){


                #Initialises the variables
                $name = $user.Name            
                $givenname = $user.Vorname
                $surname = $user.Nachname
                $email = $user.Email
                $password = $passwordinput | ConvertTo-SecureString -AsPlainText -Force
                $displayname = $givenname + " " + $surname  #evtl csv 
                $userprincipalname = $name + "@" + $domain
                $OU = "OU=" + $ouname + ",DC=" + $oudomain + ",DC=" + $outld
                          
                
                #Shows the neat loading animation (remove to speed up the process)
                Write-Host "Creating User: "$name -nonewline
                For($i=0; $i -le 3; $i++){Write-Host "." -nonewline;  Start-Sleep -s 0.75}
                Write-Host " "
                
                #Creates the AD-Users by taking the recent variables and their corresponding parameters
                New-ADUser -SamAccountName $name -Name $name -GivenName $givenname -Surname $surname -EmailAddress $email -DisplayName $displayname -UserPrincipalName $userprincipalname -Path $ou -AccountPassword $password -ChangePasswordAtLogon $False -PasswordNeverExpires $True -Enabled $True
                }}

        catch [System.Exception] {
        
        if() # TODO Catchmessages compare + silent continue
        
        }



        
         catch [ADIdentityAlreadyExistsException] {
            Write-Host "Error: User already exists!" -foreground red 
            }

        catch [ParameterBindingValidationException] {
            Write-Host "Error: There are no users in the csv file!" -foreground red
            Write-Host "Did you use the correct delimiter?" -foreground red
            break
        }

        
        catch [ADPasswordComplexityException] {
            Write-Host "Error: The chosen default password is too weak!" -foreground red
            break 
        }
          
        catch [ADException] {
            If($Error.contains()){Write-Host "User already in another Organistation-Unit" -foreground red}
            break
        }

        

        catch {
            Write-Host "An error occured..." -foreground red
            Write-Host($error[0].ToString() ) -foreground red 
            break
        }
        

       
        #Outputs a message in case of successful creation        
         Write-Host `n"****************************"
         Write-Host    "User(s) successfully created" -foreground green
         Write-Host    "****************************"
            break}

    #Outputs a goodbye message and exits the script
    ElseIf($prompt -eq $cancel) {
                Write-Host `n "Goodbye! Thanks for using my script!" -foreground yellow
                break}
    
    Else{
        Write-Host "Bad input!" -foreground red}
}
